### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by karzler** [tapkey/TapkeyCocoaPods#1]
With Xcode updated at version 10.2, the importing TapkeyMobileLib fails.

**Comment by minichma** [comment]
We're working on it and will hopefully provide an updated version soon.

**Comment by L6Echo** [comment]
Swift 4.2 and older is not ABI stable and it is necessary to use the same Swift compiler version like the linked framework.

Swift 5, which is already available with Xcode 10.2, is ABI stable. Internally we have already updated to Swift 5, but for releases we are using Azure Devops. Xcode 10.2 is still missing on Azure Devops, but Microsoft is working on it.

https://github.com/Microsoft/azure-pipelines-image-generation/issues/815

**Comment by koystinen** [comment]
@karzler change Build Step property "XCode version" from "Xcode 10" to "Specify path", and setting "Xcode developer path" to /Applications/Xcode_10.1.app , as means for running build using previous 10.1 version - resolved this issue for us. 
When code and its dependencies are upgraded to Swift 5 then you can revert the change.

**Comment by L6Echo** [comment]
We published the version 1.15.12.0 of the sdk, which was built with Swift 5.0.
