### ISSUE TITLE
TKMUserManager.logInAsync -> Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Psiiirus** [tapkey/TapkeyCocoaPods#2]
Hiya,

I'm trying to implement the mobile SDK but if I call TKMUserManager.logInAsync  I get this error 
`Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value`

I already tried to find some solutions but nothing worked so far - maybe someone can give me a hint what am i doing wrong.

<img width="1555" alt="Bildschirmfoto 2022-01-26 um 14 10 29" src="https://user-images.githubusercontent.com/593363/151170483-6608d655-4fbb-4856-9356-a32a7685bac6.png">
<img width="1555" alt="Bildschirmfoto 2022-01-26 um 14 07 35" src="https://user-images.githubusercontent.com/593363/151170487-407ed0af-06f5-4196-aaaa-1972b474f4a2.png">

<img width="1555" alt="Bildschirmfoto 2022-01-26 um 14 21 38" src="https://user-images.githubusercontent.com/593363/151170470-e5bf0f51-1c56-456e-8960-3aba5d9088ff.png">

**Comment by L6Echo** [comment]
Hi,
it seems to be a threading issue. You are calling "userManager.login()" on some worker thread. The mobile SDK is switching threads when asynchronous stuff is done, and tries to access the `OperationQueue.current` for that. But this is nil.

In general is the mobiles SDK api designed to be called on the main thread. The Promise pattern ensures, that the main thread will not be blocked.

**Comment by Psiiirus** [comment]
Thanks for your answer!

I was wondering if there is an easy way to move a method execution to the main thread or does this depend on the React native bridge code?
I actually already told the module class to explicitly load in main thread.
[https://reactnative.dev/docs/native-modules-ios](https://reactnative.dev/docs/native-modules-ios)

**Comment by L6Echo** [comment]
I am not familiar with reactnative, but this seems to be the way to go:
https://reactnative.dev/docs/native-modules-ios#threading

for testing purposes you could probably use 
```
DispatchQueue.main.async {
    
}
```

to switch to the main queue

**Comment by Psiiirus** [comment]
Ah i see ... thought "requiresMainQueueSetup" is the same ,

And thanks for the Swift syntax!
